apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsc-torrent
  namespace: jsc-ns

spec:
  selector:
    matchLabels:
      app: jsc-torrent
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: jsc-torrent
        tier: frontend
    spec:
      volumes:
      - name: jsc-nfs
        nfs:
          server: 192.168.1.120
          path: /data/nfs-01

      containers:
      - name: jsc-transmission
        image: jscdroiddev/jsc-transmission:latest
        imagePullPolicy: Always

        env:
        - name: TZ
          value: "Asia/Bangkok"
        - name: INCOMPLETE_DIR
          value: "/opt/transmission/incomplete"
        - name: CONFIG_DIR
          value: "/opt/transmission/config"
        - name: TRANSMISSION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jsc-pt-secret
              key: transmission_password
        - name: DOWNLOAD_DIR
          value: "/opt/transmission/Movies"
        - name: ALLOWED_IP
          value: "127.0.0.1,192.168.1.*,10.42.*.*"
        ports:
          - containerPort: 9091
        resources:
          limits:
            cpu: "1024m"
            memory: "2Gi"
          requests:
            cpu: "1024m"
            memory: "1Gi"
        volumeMounts:
          - name: jsc-nfs
            mountPath: /opt/transmission
