apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rochefolle-pv-claim
  namespace: jsc-ns
  labels:
    app: rochefolle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi