apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsc-gs-pv-claim
  namespace: jsc-ns
  labels:
    app: jsc-gs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
