apiVersion: v1
kind: Service
metadata:
  name: jsc-mu-game-svc
  namespace: jsc-ns
  labels:
    app: jsc-mu-game-app
spec:
  type: ClusterIP
  ports:
    - port: 8889
      targetPort: 80
  selector:
    app: jsc-mu-game-app
    tier: frontend
