apiVersion: v1
kind: Service
metadata:
  name: rochefolle
  namespace: jsc-ns
  labels:
    app: rochefolle
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: rochefolle
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rochefolle-pv-claim
  namespace: jsc-ns
  labels:
    app: rochefolle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rochefolle
  namespace: jsc-ns
  labels:
    app: rochefolle
spec:
  selector:
    matchLabels:
      app: rochefolle
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: rochefolle
        tier: frontend
    spec:
      containers:
      - image: nginx:latest
        name: rochefolle
        resources:
          requests:
            ephemeral-storage: "400Mi"
            memory: "200Mi"
          limits:
            ephemeral-storage: "500Mi"
            memory: "250Mi"
        ports:
        - containerPort: 80
          name: rochefolle
        volumeMounts:
        - name: rochefolle-persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: rochefolle-persistent-storage
        persistentVolumeClaim:
          claimName: rochefolle-pv-claim
