apiVersion: v1
kind: Service
metadata:
  name: hdc-wp
  namespace: jsc-ns
  labels:
    app: hdc-wp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hdc-wp
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdc-wp-pv-claim
  namespace: jsc-ns
  labels:
    app: hdc-wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdc-wp
  namespace: jsc-ns
  labels:
    app: hdc-wp
spec:
  selector:
    matchLabels:
      app: hdc-wp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: hdc-wp
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: hdc-wp
        resources:
          requests:
            ephemeral-storage: "1Gi"
            memory: "200Mi"
          limits:
            ephemeral-storage: "2Gi"
            memory: "250Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: hdc-wp-mariadb
        - name: WORDPRESS_DB_NAME
          value: hdc-wp-db
        - name: WORDPRESS_DB_USER
          value: hdc-wp-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hdc-secret
              key: wp_password
        ports:
        - containerPort: 80
          name: hdc-wp
        volumeMounts:
        - name: hdc-wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: hdc-wp-persistent-storage
        persistentVolumeClaim:
          claimName: hdc-wp-pv-claim
