apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: jsc-ns
  name: letsencrypt-prod
spec:
  acme:
    email: <your-email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: jsc-home-certificate
    solvers:
    - http01:
        ingress:
          class: nginx