apiVersion: apps/v1
kind: Deployment
metadata:
  name: sawan
  namespace: jsc-ns
  labels:
    app: sawan
spec:
  selector:
    matchLabels:
      app: sawan
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: sawan
        tier: frontend
    spec:
      containers:
      - image: jscdroiddev/sawanio:latest
        name: sawan
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Bangkok
        resources:
          requests:
            ephemeral-storage: "1Gi"
            memory: "200Mi"
          limits:
            ephemeral-storage: "2Gi"
            memory: "250Mi"
        ports:
        - containerPort: 3000
          name: sawan