apiVersion: v1
kind: Service
metadata:
  name: sawan-svc
  namespace: jsc-ns
  labels:
    app: sawan
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: sawan
    tier: frontend
  externalIPs:
  - 192.168.1.132
