apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: narok-wp-pv-claim
  namespace: jsc-ns
  labels:
    app: narok-wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: narok-mariadb-pv-claim
  namespace: jsc-ns
  labels:
    app: narok-wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi