apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsc-pt-pv-claim
  namespace: jsc-ns
  labels:
    app: jsc-plex-torrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi