apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsc-plex-torrent
  namespace: jsc-ns

spec:
  selector:
    matchLabels:
      app: jsc-plex-torrent
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: jsc-plex-torrent
        tier: frontend
    spec:
      volumes:
      - name: jsc-pt-volume
        persistentVolumeClaim:
          claimName: jsc-pt-pv-claim

      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chown","-R","1000:1000", "/opt/transmission"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: jsc-pt-volume
          mountPath: /opt/transmission

      containers:
      - name: jsc-transmission
        image: jscdroiddev/jsc-transmission:latest
        imagePullPolicy: Always

        env:
        - name: TZ
          value: "Asia/Bangkok"
        - name: INCOMPLETE_DIR
          value: "/opt/transmission/incomplete"
        - name: CONFIG_DIR
          value: "/opt/transmission/config"
        - name: TRANSMISSION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jsc-pt-secret
              key: transmission_password
        - name: DOWNLOAD_DIR
          value: "/opt/transmission/Movies"
        - name: ALLOWED_IP
          value: "127.0.0.1,192.168.1.*,10.42.*.*"
        ports:
          - containerPort: 9091
        resources:
          limits:
            cpu: "1024m"
            memory: "2Gi"
          requests:
            cpu: "1024m"
            memory: "1Gi"
        volumeMounts:
          - name: jsc-pt-volume
            mountPath: /opt/transmission

      - name: jsc-plex
        image: plexinc/pms-docker
        imagePullPolicy: Always

        env:
        - name: TZ
          value: "Asia/Bangkok"
        - name: INCOMPLETE_DIR
          value: "/opt/transmission/incomplete"
        - name: CONFIG_DIR
          value: "/opt/transmission/config"
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: jsc-pt-secret
              key: plex_claim_token
        - name: DOWNLOAD_DIR
          value: "/opt/transmission/Movies"
        - name: ALLOWED_IP
          value: "127.0.0.1,192.168.1.*,10.42.*.*"
        ports:
          - containerPort: 9091
        resources:
          limits:
            cpu: "1024m"
            memory: "2Gi"
          requests:
            cpu: "1024m"
            memory: "1Gi"
        volumeMounts:
          - name: jsc-pt-volume
            mountPath: /opt/transmission