apiVersion: v1
kind: Service
metadata:
  name: jsc-pt-svc
  namespace: jsc-ns
spec:
  selector:
    app: jsc-plex-torrent
  ports:
  - port: 9091
    name: jsc-transmission
    targetPort: 9091
  externalIPs:
  - 192.168.1.132