apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gold-price-pv-claim
  namespace: jsc-ns
  labels:
    app: gold-price
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
